# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20160927_1157'),
        ('financial_activities', '0006_auto_20161006_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='submission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='submissions.SubmissionAttributes'),
            preserve_default=False,
        ),
    ]
