# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 15:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0010_financialaccountsbyprogramactivityobjectclass_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='object_class',
            field=models.ForeignKey(db_column='object_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefObjectClassCode'),
        ),
    ]
